name: basic_chat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.7.5
  analyzer: ^0.41.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  